version: '3'

volumes:
  dynamodb_data: {}

services:
  claudia: &claudia
    build:
      context: .
      dockerfile: ./claudia/Dockerfile
    working_dir: /home/node/app
    volumes:
      - ../../:/home/node/app
    env_file:
      - claudia/.env
    command:
      - /bin/sh
      - -c
      - |
        sh claudia.config.sh
        npm install
        chown -R ${SERVICE_PERMISSIONS} /home/node/app
        npm ${YARN_COMMAND}
        chown -R ${SERVICE_PERMISSIONS} /home/node/app

  claudia_cmd:
    <<: *claudia

  claudia_api:
    <<: *claudia
    ports:
      - "3000:3000"
    command:
      - /bin/sh
      - -c
      - |
        sh claudia.config.sh
        npm run local:api

  dynamodb:
    image: amazon/dynamodb-local
    volumes:
      - dynamodb_data:/home/dynamodblocal
    command: '-Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -dbPath /home/dynamodblocal'



